fastlane_version '2.170.0'

default_platform :ios

app_name = 'Greenlight'
app_identifier = 'com.greenlightready.app'

platform :ios do
  desc 'Deploy ios app on appstore'
end

platform :android do
  desc 'Deploy android app on play store'
end
