require:
  - ./rubocop/rubocop
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7
  TargetRailsVersion: 6.0
  Exclude:
    - 'rubocop/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'db/migrate/**/*'
    - 'db/fixtures/**/*'
    - 'db/schema.rb'
    - 'tmp/**/*'
    - 'bin/**/*'
  CacheRootDirectory: tmp
  MaxFilesInCache: 18000
  NewCops: enable

Cop/AvoidKeywordArgumentsInSidekiqWorkers:
  Enabled: true
  Include:
    - 'app/workers/**/*'

Layout/ArgumentAlignment:
  Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
    Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Rails/DynamicFindBy:
  Enabled: false

RSpec/DescribedClass:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: false

RSpec/ExampleLength:
  Enabled: false

# You should really be using anywhere near 10
RSpec/MultipleMemoizedHelpers:
  Max: 10

# We use database ON DELETEs instead
Rails/HasManyOrHasOneDependent:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ImplicitExpect:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

# Frozen String Literal
Style/FrozenStringLiteralComment:
  Enabled: true
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config/**/*'
    - 'danger/**/*'
    - 'db/**/*'
    - 'lib/tasks/**/*'
    - 'rubocop/**/*'
    - 'scripts/**/*'

Style/RedundantSelf:
  Enabled: false

# This cop checks whether some constant value isn't a
# mutable literal (e.g. array or hash).
Style/MutableConstant:
  Enabled: true
  Exclude:
    - 'db/migrate/**/*'
    - 'db/post_migrate/**/*'

Style/Lambda:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false
