jackson:
  serialization-inclusion: always

# todo separate dev/prod dbs
# todo set actual db credentials
datasources:


  default:
    username: greenlight
    password: ggrreenn
    auto-commit: true
    jdbc-url: jdbc:postgresql://localhost:13700/covid
    allow-pool-suspension: false
    # max concurrent connections
    maximum-pool-size: 500
    minimum-idle: 20
    # 10 second timeout
    connection-timeout: 10000
    driver-class-name: org.postgresql.Driver

jpa:
  default:
    entity-scan:
      enabled: true
      packages:
        - 'greenlight.entities'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
        hbm2ddl:
          auto: create-drop
        show_sql: true
