micronaut:
  application:
    name: api
  server:
    ssl:
      enabled: false
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:SUPER_SECRET_CODE}"'
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/greenlight_wip
    driverClassName: org.postgresql.Driver
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      enabled: true
      packages:
        - greenlight.entities
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
        physical_naming_strategy: greenlight.etc.CamelToSnakeCaseNamingStrategy

liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yml
