Zmetrics:
  security:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:SUPER_SECRET_DEVELOPMENT_KEY}"'
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/greenlight_development

liquibase:
    datasources:
        default:
            default-schema: greenlight_development
