micronaut:
  application:
    name: api
  metrics:
    export:
      newrelic:
        enabled: true
        apiKey: ${NEWRELIC_API_KEY}
        accountId: ${NEWRELIC_ACCOUNT_ID}
        step: PT1M
    enabled: true
  server:
    ssl:
      enabled: 'true'
  security:
    authentication: bearer
    token:
      jwt:
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOne}"'
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/greenlight_wip
    driverClassName: org.postgresql.Driver
    username: postgres
    password: ''
    schema-generate: CREATE_DROP
    dialect: POSTGRES

jpa:
  default:
    entity-scan:
      enabled: true
      packages:
        - greenlight.entities
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        physical_naming_strategy: greenlight.etc.CamelToSnakeCaseNamingStrategy

acme:
  enabled: 'true'
  tos-agree: 'true'
