local:
  service: Disk
  root: <%= Rails.root.join('storage') %>

test:
  service: Disk
  root: <%= Rails.root.join('tmp/storage') %>

amazon:
  service: S3
  access_key_id: <%= Greenlight::AWS_ACCESS_KEY_ID %>
  secret_access_key: <%= Greenlight::AWS_SECRET_ACCESS_KEY %>
  bucket: <%= Greenlight::AWS_BUCKET %>
  region: <%= Greenlight::AWS_REGION %>
