source 'https://rubygems.org'

ruby '2.7.1'

#
# Core
#

# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 4.1'
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 6.0.3', '>= 6.0.3.2'
# Simple, efficient background processing for Ruby
gem 'sidekiq', '< 7'
# Enables to set jobs to be run in specified time
gem 'sidekiq-cron', '1.2'

#
# Engines and Middlewares
#

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors'
# The Routing Tree Web Toolking
gem 'roda'
# Add http authorization methods to Roda
gem 'roda-http-auth'

#
# Performance
#

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', require: false
# C implementation of Active Support's String#blank?
gem 'fast_blank', platform: :mri
# C extensions for escaping text
gem 'fast_xs', platform: :mri
# Generic swappable back-end for JSON
gem 'multi_json'
# Optimized JSON
gem 'oj', platform: :mri
# Blazing-fast-cross-platform-monkey-patch-free string XOR
gem 'xorcist'

#
# Misc
#

# What ActiveModel left out
gem 'active_attr'
# Password encryption
gem 'bcrypt', '~> 3.1.7'
# Enumerated attributes
gem 'enumerize'
# Exception notifier
gem 'exception_notification'
# Simple, but flexible HTTP client library
gem 'faraday'
# A lightning fast JSON:API serializer for Ruby Objects.
gem 'fast_jsonapi'
# JSON web tokens
gem 'jwt'
# Return JSON API errors
gem 'jsonapi_errors_handler', git: 'https://github.com/fny/jsonapi_errors_handler.git'
# Tame Rails' default policy to log everything
gem 'lograge'
# Phone validations
gem 'phonelib'
# SMS API and Voice API platform
gem 'plivo'
# The express way to send email 
gem 'pony'
# Advanced seed data handling for Rails
gem 'seed-fu', '~> 2.3'
# Twilio Sendgrid Email API
gem 'sendgrid-ruby'
# Performance monitoring
gem 'skylight'
# Email validations
gem 'valid_email2'

group :development, :test do
  # Annotate Rails classes with schema and routes info
  gem 'annotate'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platforms: [:mri, :mingw, :x64_mingw]
  # Load environment variables from `.env`
  gem 'dotenv-rails'
  # Object generation framework
  gem 'fabrication'
  # Library for generating fake data
  gem 'faker'
  # `rails c` alternative and runtime developer console
  gem 'pry-rails'
  # Launch a pry session when a test fails
  gem 'pry-rescue'
  # Move up and down the stack with pry
  gem 'pry-stack_explorer'
  # Behavior driven development in Ruby
  gem 'rspec'
  gem 'rspec-rails'
  # 2x Testing Speed
  gem 'parallel_tests'
  # Test one-liners for common Rails functionality
  gem 'shoulda-matchers'
end

group :development do
  # Help to kill N+1 queries and unused eager loading
  gem 'bullet', '~> 6.1.0'
  # Manage Procfile-based apps
  gem 'foreman', require: false
  # Listens for file modifications, used by Spring
  gem 'listen', '~> 3.2'
  # Preview email in the default browser
  # gem 'letter_opener', group: :development
  # A Ruby language server and code formatter
  gem 'rubocop', require: false
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
  # A Ruby language server
  gem 'solargraph', require: false
end
